# DESCRIPTION: GitLab CI/CD for libRetro (NOT FOR GitLab-proper)

##############################################################################
################################# BOILERPLATE ################################
##############################################################################

# Core definitions
.core-defs:
  variables:
    JNI_PATH: target-libretro
    CORENAME: bsnes_mercury_performance
    PROFILE: performance

.core-defs-balanced:
  extends: .core-defs
  variables:
    CORENAME: bsnes_mercury_balanced
    PROFILE: balanced

.core-defs-accuracy:
  extends: .core-defs
  variables:
    CORENAME: bsnes_mercury_accuracy
    PROFILE: accuracy

# Inclusion templates, required for the build to work
include:
  ################################## DESKTOPS ################################
  # Windows 64-bit
  - project: 'libretro-infrastructure/ci-templates'
    file: '/windows-x64-mingw.yml'

  # Windows 32-bit
  - project: 'libretro-infrastructure/ci-templates'
    file: '/windows-i686-mingw.yml'

  # Linux 64-bit
  - project: 'libretro-infrastructure/ci-templates'
    file: '/linux-x64.yml'

  # Linux 32-bit
  - project: 'libretro-infrastructure/ci-templates'
    file: '/linux-i686.yml'

  ################################## CELLULAR ################################
  # Android
  - project: 'libretro-infrastructure/ci-templates'
    file: '/android-jni.yml'

# Stages for building
stages:
  - build-prepare
  - build-shared
  - build-static

###############################
## bsnes_mercury_performance ##
###############################

# Desktop

# Linux 64-bit
libretro-build-linux-x64:
  extends:
    - .libretro-linux-x64-make-default
    - .core-defs

# Linux 32-bit
libretro-build-linux-i686:
  extends:
    - .libretro-linux-i686-make-default
    - .core-defs

# Windows 64-bit
libretro-build-windows-x64:
  extends:
    - .libretro-windows-x64-mingw-make-default
    - .core-defs

# Windows 32-bit
libretro-build-windows-i686:
  extends:
    - .libretro-windows-i686-mingw-make-default
    - .core-defs

# Android
android-armeabi-v7a:
  extends:
    - .libretro-android-jni-armeabi-v7a
    - .core-defs

android-arm64-v8a:
  extends:
    - .libretro-android-jni-arm64-v8a
    - .core-defs

android-x86_64:
  extends:
    - .libretro-android-jni-x86_64
    - .core-defs

android-x86:
  extends:
    - .libretro-android-jni-x86
    - .core-defs

############################
## bsnes_mercury_balanced ##
############################

# Desktop
# Linux 64-bit
libretro-build-linux-x64-balanced:
  extends:
    - .libretro-linux-x64-make-default
    - .core-defs-balanced

# Linux 32-bit
libretro-build-linux-i686-balanced:
  extends:
    - .libretro-linux-i686-make-default
    - .core-defs-balanced

# Windows 64-bit
libretro-build-windows-x64-balanced:
  extends:
    - .libretro-windows-x64-mingw-make-default
    - .core-defs-balanced

# Windows 32-bit
libretro-build-windows-i686-balanced:
  extends:
    - .libretro-windows-i686-mingw-make-default
    - .core-defs-balanced
    
# Android
android-armeabi-v7a-balanced:
  extends:
    - .libretro-android-jni-armeabi-v7a
    - .core-defs-balanced

android-arm64-v8a-balanced:
  extends:
    - .libretro-android-jni-arm64-v8a
    - .core-defs-balanced

android-x86_64-balanced:
  extends:
    - .libretro-android-jni-x86_64
    - .core-defs-balanced

android-x86-balanced:
  extends:
    - .libretro-android-jni-x86
    - .core-defs-balanced

############################
## bsnes_mercury_accuracy ##
############################

# Desktop

# Linux 64-bit
libretro-build-linux-x64-accuracy:
  extends:
    - .libretro-linux-x64-make-default
    - .core-defs-accuracy

# Linux 32-bit
libretro-build-linux-i686-accuracy:
  extends:
    - .libretro-linux-i686-make-default
    - .core-defs-accuracy

# Windows 64-bit
libretro-build-windows-x64-accuracy:
  extends:
    - .libretro-windows-x64-mingw-make-default
    - .core-defs-accuracy

# Windows 32-bit
libretro-build-windows-i686-accuracy:
  extends:
    - .libretro-windows-i686-mingw-make-default
    - .core-defs-accuracy

# Android
android-armeabi-v7a-accuracy:
  extends:
    - .libretro-android-jni-armeabi-v7a
    - .core-defs-accuracy

android-arm64-v8a-accuracy:
  extends:
    - .libretro-android-jni-arm64-v8a
    - .core-defs-accuracy

android-x86_64-accuracy:
  extends:
    - .libretro-android-jni-x86_64
    - .core-defs-accuracy

android-x86-accuracy:
  extends:
    - .libretro-android-jni-x86
    - .core-defs-accuracy
